name: CI for front and back end
on: [push]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: OTC-medical-supplies
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Build and run docker compose
        run: docker compose up --build


  # deploy:
  #   needs: test 
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to AWS EC2
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.REMOTE_HOST }}
  #         username: ${{ secrets.REMOTE_USER }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         script: |
  #           cd cicd-docker
  #           git pull
  #           docker-compose up --build --detach
  #           ping 127.0.0.1 -c 4