name: Docker build app
on: [push]

jobs:
  compose:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code
        uses: actions/checkout@v4
      
      - name: Create env file
        run: |
          mkdir -p back-end/inventory
          echo "${{ secrets.INVENTORY_ENV }}" > back-end/inventory/.env
      # - name: debug
      #   run: 
      #     pwd
      #     ls -la

      - name: Build and run docker compose
        run: docker compose up --build -d

