name: CI for front and back end
on: [push]

jobs:
  # build: 
#     runs-on: ubuntu-latest

#     steps: 
#       - name: Checkout repo
#       - uses: actions/checkout@v5
# # -------- Build Front End -------------- 
#       #   with:
#       #     node-version: "20.x"
#       # - run: npm ci
#       # - run: npm run start & 

  test:
    runs-on: ubuntu-latest
    defaults:
      run: 
        working-directory: front-end
    steps: 
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          
      - name: install dependencies and run tests
        run: npm ci
        run: npm t

  # deploy:
  #   needs: test 
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Deploy to AWS EC2
  #       uses: appleboy/ssh-action@master
  #       with:
  #         host: ${{ secrets.REMOTE_HOST }}
  #         username: ${{ secrets.REMOTE_USER }}
  #         key: ${{ secrets.SSH_PRIVATE_KEY }}
  #         script: |
  #           cd cicd-docker
  #           git pull
  #           docker-compose up --build --detach
  #           ping 127.0.0.1 -c 4